<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>promise的几个关键问题</title>
		<script>
			/* 
         改变promise状态和指定回调函数谁先谁后？
            (1)都有可能，正常情况下是先指定回调再改变状态，但也可以先改状态再指定回调
            (2)如何先改状态再指定回调？
               1 在执行器中直接调用resolve() / reject()
               2 延迟更长时间才调用then()
            (3)什么时候才能得到数据？
               1 如果先指定的回调，那当状态发生改变时，回调函数就会调用，得到数据
               2 如果先改变的状态，那当指定回调时，回调函数就会调用，得到数据
         */
			//exactor执行器函数是同步的，.then()是同步的，then里面的是异步的

			//常规：先指定回调函数，后改变状态
			new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve(1); //后改变的状态（同时指定数据），异步执行回调函数
				}, 1000);
			}).then(
				//先指定回调函数，保存当前指定的回调函数
				(value) => {},
				(reason) => {
					console.log('reason', reason);
				}
			);

			//如何先改变状态，后指定回调函数
			new Promise((resolve, reject) => {
				resolve(1); //先改变的状态（同时指定数据），异步执行回调函数
			}).then(
				//后指定回调函数，异步执行回调函数
				(value) => {},
				(reason) => {
					console.log('reason', reason);
				}
			);

			const p = new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve(1);
				}, 1000);
			});

			setTimeout(() => {
				p.then(
					(value) => {},
					(reason) => {
						console.log('reason', reason);
					}
				);
			}, 1100);
		</script>
	</head>
	<body>
		<script>
			console.log('----------------------------------------------');
			/* 
         promise.then(）返回的新promise的结果状态由什么决定？
            (1)简单表达：由then()指定的回调函数执行的结果决定
            (2)详细表达：
               1 如果抛出异常，新promise变为rejected，reason为拋出的异常
               2 如果返回的是非promise的任意值，新promise变为resolved， value为返回的值
               3 如果返回的是另一个新promise，此promise的结果就会成为新promise的结果
         */
			//!!! 每个函数都有一个返回值return ，默认undefined ，不写或只写return就会默认返回undefined

			new Promise((resolve, reject) => {
				// resolve(1);
				reject(2);
			})
				.then(
					(value) => {
						console.log('value1', value);
						// return 2;
						// return Promise.resolve(3);
						// return Promise.reject(4);
						// throw 5;
					},
					(reason) => {
						console.log('reason1', reason);
						// return 2;
						// return Promise.resolve(3);
						// return Promise.reject(4);
						throw 5;
					}
				)
				.then(
					(value) => {
						console.log('value2', value);
					},
					(reason) => {
						console.log('reason2', reason);
					}
				);
		</script>
		<script>
			/* 
         promise异常传透？
            (1) 使用promise的then链式调用时，可以在最后指定失败的回调
            (2) 前面任何操作出了异常，都会传到最后失败的回调中处理

         7.中断promise链？
            (1)当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数
            (2)办法：在回调函数中返回一个 pending 状态的promise对象

         */
			console.log('---------------------------');

			new Promise((resolve, reject) => {
				// resolve(1);
				reject(9);
			})
				.then(
					(value) => {
						console.log('value1', value);
						return 2;
					},
					(reason) => {
						throw reason; //默认写法
					}
				)
				.then(
					(value) => {
						console.log('value2', value);
						return 3;
					},
					(reason) => Promise.reject(reason)
				)
				.catch((reason) => {
					console.log('reason1', reason);
					//throw reason
					// return Promise.reject(reason);
					return new Promise((resolve, reject) => {}); //返回pending的promise，中断promise链
				})
				.then(
					(value) => {
						console.log('value3', value);
					},
					(reason) => {
						console.log('reason2', reason);
					}
				);
		</script>
	</body>
</html>
