<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>自定义Promise</title>
		<!-- <script src="../lib/Promise.js"></script> -->
		<script src="../lib//Promise_class.js"></script>
	</head>
	<body>
		<!-- 	<script>
			const p = new Promise((resolve, reject) => {
				setTimeout(() => {
					// resolve(1);
					reject(2);
					console.log('reject()改变状态之后');
				}, 100);
			});
			p.then(
				(value) => {
					console.log('onResolved() 1', value);
				},
				(reason) => {
					console.log('onRejected() 1', reason);
				}
			);
			p.then(
				(value) => {
					console.log('onResolved() 2', value);
				},
				(reason) => {
					console.log('onRejected() 2', reason);
				}
			);
		</script> -->
		<!-- <script>
			const p = new Promise((resolve, reject) => {
				setTimeout(() => {
					// resolve(1);
					reject(2);
				}, 100);
			})
				.then(
					(value) => {
						console.log('onResolved() 1', value);
					},
					(reason) => {
						console.log('onRejected() 1', reason);
						// return 3;
						// throw 4
						return new Promise((resolve, reject) => reject(5));
					}
				)
				.then(
					(value) => {
						console.log('onResolved() 2', value);
					},
					(reason) => {
						console.log('onRejected() 2', reason);
						throw 6;
					}
				)
				.catch((reason) => {
					console.log('onRejected() 3', reason);
					return new Promise((resolve, reject) => {});
				})
				.then(
					(value) => {
						console.log('onResolved() 4', value);
					},
					(reason) => {
						console.log('onRejected() 4', reason);
						throw 6;
					}
				);
		</script> -->

		<script>
			const p1 = Promise.resolve(2);
			const p2 = Promise.resolve(Promise.resolve(3));
			const p3 = Promise.resolve(Promise.reject(4));

			/* 	p1.then((value) => {
				console.log('p1', value); //如果是一般值，p1成功，value就是这个值
			});
			p2.then((value) => {
				console.log('p2', value); //如果是成功的promise，p2成功，value是这个promise的value
			});
			p3.catch((reason) => {
				console.log('p3', reason); //如果是失败的promise，p3失败，reason是这个promise的reason
			}); */

			const pAll = Promise.all([p1, p2, 7]);
			pAll.then(
				(value) => {
					console.log('all onResolved()', value);
				},
				(reason) => {
					console.log('all onRejected()', reason);
				}
			);

			const pRace = Promise.race([p2, 7, p1, p3]);
			pRace.then(
				(value) => {
					console.log('race onResolved()', value);
				},
				(reason) => {
					console.log('race onRejected()', reason);
				}
			);

			const p6 = Promise.resolveDelay(66, 2000);
			const p7 = Promise.rejectDelay(77, 2000);
			p6.then((value) => {
				console.log('p6', value);
			});
			p7.catch((reason) => {
				console.log('p7', reason);
			});
		</script>
	</body>
</html>
